const getters = {
  fileName: state => state.book.fileName,
  menuVisible: state => state.book.menuVisible,
  settingVisible: state => state.book.settingVisible,
  defaultFontSize: state => state.book.defaultFontSize,
  defaultFontFamily: state => state.book.defaultFontFamily,
  fontFamilyVisible: state => state.book.fontFamilyVisible,
  defaultTheme: state => state.book.defaultTheme,
  bookAvailable: state => state.book.bookAvailable,
  progress: state => state.book.progress,
  section: state => state.book.section,
  isPaginating: state => state.book.isPaginating,
  currentBook: state => state.book.currentBook,
  navigation: state => state.book.navigation,
  cover: state => state.book.cover,
  metadata: state => state.book.metadata,
  paginate: state => state.book.paginate,
  pagelist: state => state.book.pagelist,
  offsetY: state => state.book.offsetY,
  isBookMark: state => state.book.isBookMark,
  speakingIconBottom: state => state.book.speakingIconBottom,
  hotSearchOffsetY: state => state.hotSearchOffsetY,
  flapCardVisible: state => state.flapCardVisible,
  isEditMode: state => state.isEditMode,
  shelfList: state => state.shelfList,
  shelfSelected: state => state.shelfSelected,
  shelfTitleVisible: state => state.shelfTitleVisible
}

export default getters
